### ISSUE TITLE
Text domains for color codes?

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/rise-lite#3]
/rise-lite/includes/customizer.php on line 38  .... culorile au `esc_html__` ca si cum se voiau a fi traduse ... not right.

**Comment by tacoverdo** [comment]
This leads to color codes being translatable, see here:
<img width="952" alt="translations___dutch___rise_lite___glotpress_ _wordpress" src="https://cloud.githubusercontent.com/assets/5147598/17498637/e4627f94-5dc8-11e6-9ff8-3f31f77bcef2.png">

Easiest fix would be to replace [`esc_html__()`](https://developer.wordpress.org/reference/functions/esc_html__/) with [`esc_html()`](https://codex.wordpress.org/Function_Reference/esc_html).
